// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHgS5Q_-WYkWM4ywwskAP0l4fY1YZ5hb4',
    appId: '1:318202798528:web:7f7e23c78deb6e1a40e825',
    messagingSenderId: '318202798528',
    projectId: 'examen-497c1',
    authDomain: 'examen-497c1.firebaseapp.com',
    storageBucket: 'examen-497c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVS7nHNj7XGWI2YEnuKmjUthr1la8Prg',
    appId: '1:318202798528:android:cd8c3f195d5b42a440e825',
    messagingSenderId: '318202798528',
    projectId: 'examen-497c1',
    storageBucket: 'examen-497c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ecIlxOS1YcoxiCduIrpWYJau8tiYjy8',
    appId: '1:318202798528:ios:1d9c2051aad3800f40e825',
    messagingSenderId: '318202798528',
    projectId: 'examen-497c1',
    storageBucket: 'examen-497c1.appspot.com',
    iosBundleId: 'com.example.exaameen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ecIlxOS1YcoxiCduIrpWYJau8tiYjy8',
    appId: '1:318202798528:ios:1d9c2051aad3800f40e825',
    messagingSenderId: '318202798528',
    projectId: 'examen-497c1',
    storageBucket: 'examen-497c1.appspot.com',
    iosBundleId: 'com.example.exaameen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHgS5Q_-WYkWM4ywwskAP0l4fY1YZ5hb4',
    appId: '1:318202798528:web:76b1b0d361af274140e825',
    messagingSenderId: '318202798528',
    projectId: 'examen-497c1',
    authDomain: 'examen-497c1.firebaseapp.com',
    storageBucket: 'examen-497c1.appspot.com',
  );
}
